"""P11.2: write docs/DEMO_SCRIPT.md, the five-minute demo, with every number read from the saved results.

Usage:  python -m scripts.demo_script

Reads data/results/v2/index.json (the nightly demo results) and data/results/results.json (the gates), so the script
never states a number that is not in a results file (plan section 0.7). Regenerate after every nightly run.
"""
from __future__ import annotations

import json
import math
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
V2 = ROOT / "data" / "results" / "v2"
OUT = ROOT / "docs" / "DEMO_SCRIPT.md"


def _load(rel: Path) -> dict:
    return json.loads(rel.read_text(encoding="utf-8"))


def results_by(route: str, day_type: str, rule: str) -> dict | None:
    for e in _load(V2 / "index.json")["entries"]:
        if (e["route"], e.get("day_type"), e["rule"]) == (route, day_type, rule):
            return _load(V2 / f"{e['key']}.json")
    return None


# ---- numbers exactly as the dashboard shows them (frontend/src/format.ts) ----------------------------------------
# JavaScript's toFixed rounds the float's exact binary value half up, and Math.round is floor(x + 0.5); Python's round()
# rounds half to even (20.25 -> 20.2 where the screen shows 20.3), so it is not used for any number said aloud.

def one(x: float) -> str:
    """format.ts one(): String(Number(x.toFixed(1))) - one decimal, half up, trailing .0 dropped."""
    d = Decimal(x).quantize(Decimal("0.1"), rounding=ROUND_HALF_UP)
    return str(d.normalize()) if d != d.to_integral() else str(int(d))


def pct(p: float) -> str:
    """format.ts pct(): Math.round(p * 100) + '%'."""
    return f"{math.floor(p * 100 + 0.5)}%"


def raw(x) -> str:
    """The Proof page prints results.json values as stored (JavaScript String(number))."""
    return str(int(x)) if isinstance(x, float) and x.is_integer() else str(x)


def _hours(risk: dict) -> str:
    h = risk["expected_unsafe_hours"]
    return f"about {one(h['mean'])} hours (between {one(h['p10'])} and {one(h['p90'])} in 8 of 10 scenarios)"


def _verdict(fixes: dict) -> str:
    v = fixes["verdict"]
    if v["safe_action_found"]:
        label = next(o["label"] for o in fixes["outcomes"] if o["id"] == v["recommended"])
        return f"safe fix: **{label}**"
    return f"**No safe action** - {v['message'].split('.', 1)[1].strip()}" + (f" Still needs: {v['still_needs']}." if v.get("still_needs") else "")


def peak_time(risk: dict) -> str:
    """Time of day with the highest chance of unsafe voltage (read from the result, not assumed)."""
    p = risk["p_unsafe"]
    return risk["t"][max(range(len(p)), key=p.__getitem__)]


def build() -> str:
    index = _load(V2 / "index.json")
    gates = {g["gate"]: g for g in _load(ROOT / "data" / "results" / "results.json")["gates"]}
    d = index["demo_dates"]
    sun_up, sun_10 = results_by("risk", "sunny", "up_2005"), results_by("risk", "sunny", "pm10")
    fix_up, fix_10 = results_by("fixes", "sunny", "up_2005"), results_by("fixes", "sunny", "pm10")
    cloudy_10 = results_by("risk", "cloudy", "pm10")
    host = results_by("hosting", "sunny", "pm10")
    room = results_by("headroom", "sunny", "pm10")
    g1, g8 = gates["G1"]["measured"], gates["G8"]["measured"]
    far = room["locations"]["far"]["phases"] if room else {}
    near = room["locations"]["near"]["phases"] if room else {}
    lines = [
        "# GridTwin: five-minute demo script",
        "",
        f"Generated by `python -m scripts.demo_script` from `data/results` (code version {index['code_version']}). "
        "Every number below is read from a results file; regenerate after each nightly run. Draft for A and B to rehearse.",
        "",
        "Before the demo: `python -m scripts.nightly`, then start the API with `GRIDTWIN_OFFLINE=1` so a dead network "
        "cannot stop the demo. Open the dashboard on the sunny demo day "
        f"({d['sunny']}).",
        "",
        "## 1. Home: tomorrow's risk (60 s)",
        "",
        f"- Rule selector on **UP Supply Code (+/-6%)**. Level **{sun_up['level'].upper()}** from {sun_up['first_act']}; "
        f"{_hours(sun_up)} unsafe.",
        f"- Switch to +/-10% for a moment to show the shape: the chance of unsafe voltage is highest around "
        f"**{peak_time(sun_10)}** ({pct(max(sun_10['p_unsafe']))}), against {pct(sun_10['p_unsafe'][48])} at 12:00.",
        f"- Point at the calibration note: the chances are *{'slightly better than the historical average' if sun_up['calibration']['reliable'] else 'not reliable as odds'}* under this rule.",
        "",
        "## 2. Switch the rule to +/-10% (30 s)",
        "",
        f"- Same day, same street: **{sun_10['level'].upper()}** from {sun_10['first_act']}, {_hours(sun_10)}.",
        "- Say: the rule a state chooses changes the answer; every rule shows its source and how well it is verified.",
        f"- Contrast the cloudy day ({d['cloudy']}): level **{cloudy_10['level'].upper()}**.",
        "",
        "## 3. Fixes: the tournament and the honest verdict (90 s)",
        "",
        f"- +/-10%: {_verdict(fix_10)}",
        f"- UP +/-6%: {_verdict(fix_up)}",
        "- Say: every option (transformer tap, IEEE 1547 smart inverters, export limits, phase moves, switching, "
        "batteries) was replayed through the full power flow on every scenario; only fixes safe at every step count.",
        "",
        "## 4. Planning: can we approve this connection? (60 s)",
        "",
        "- Open **Planning** and **switch the rule selector to +/-10%** (it is still on UP +/-6% from step 3). The numbers "
        "below are the +/-10% results; under UP +/-6% the street has almost no room left, which is the point of step 3.",
    ]
    if room:
        def kw(phases: dict) -> str:
            # 60 kW is the top of the search (engine.headroom max_kw): reaching it means "at least 60 kW"
            return ", ".join("{} {}{} kW".format(p, "" if v["no_worse_kw"] < 60 else "at least ", one(v["no_worse_kw"]))
                             for p, v in phases.items())
        lines += [f"- Extra rooftop solar the street can take with {pct(room['adoption'])} of homes already on solar "
                  f"(no step made worse): far end {kw(far)}; next to the transformer {kw(near)}.",
                  "- Say: the place **and the phase** decide; a flat state cap cannot see either."]
    if host:
        a, b = host["without_fix"]["adoption_share"], host["with_volt_var"]["adoption_share"]
        lines += [f"- Hosting capacity (share of homes that can add solar, P10-P90): without a fix {pct(a['p10'])}-{pct(a['p90'])}; "
                  f"with standard Volt/VAR {pct(b['p10'])}-{pct(b['p90'])}."]
    lines += [
        "- In the **Connection check** form on the same page: pick the far end of the street, 5 kW, one system, best "
        "phase, then **Check this request** - read out the decision, the phase it chose and the reason on screen.",
        "",
        "## 5. Proof: how much to trust it (60 s)",
        "",
        f"- Engine checked against pandapower: {raw(g1['max_voltage_diff_v'])} V apart, {raw(g1['speedup'])} times faster (G1).",
        f"- Risk calibration (G8): +/-10% calibrated skill {raw(g8['pm10']['brier_skill_calibrated'])}; "
        f"UP +/-6% {raw(g8['up_2005']['brier_skill_calibrated'])}, on held-out days of both districts - "
        + ("passed." if gates["G8"]["status"] == "pass" else "shown as failed, not hidden."),
        "- Gates: " + ", ".join(f"{k} {v['status']}" for k, v in gates.items()) + ".",
        "- Say: a failed gate is a result, not a bug to hide.",
        "",
        "## Rules for the demo",
        "",
        "- Never say a number that is not on screen or in this script.",
        "- Say 'modeled' for forecasts and 'benchmark' for the street layout; the street is not a surveyed Indian feeder.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    OUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
